services:
  - type: web
    name: cryptext-backend
    env: python
    plan: free
    root: backend
    buildCommand: |
  pip install --upgrade pip setuptools wheel Cython
  pip install -r requirements.txt

    startCommand: gunicorn -k eventlet -w 1 app:app
