services:
  - type: web
    name: cryptext-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn -k eventlet -w 1 app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    region: frankfurt
    rootDir: backend
